title: &title my app
description: &description my app description goes here

social:
  image:

server:
  cookies: on
  session: on
  body_parsing: on
  robots_txt: off
  compression: off
  view_cache: off

manifest:
  name: *title
  short_name: *title
  description: *description
  start_url: /?utm_source=homescreen
  background_color: "#000"
  theme_color: "#27b8e8"
  display: standalone
  icons: []
    # - src:
    #   sizes:
    #   type:
